import { StyleSheet, Dimensions } from 'react-native';
import Colors from '../../../assets/Colors';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
    container: {
      flex: 1,
      height: windowHeight,
      width: windowWidth,
      paddingTop: '2%',
      backgroundColor: 'transparent',
    },
    view2: {
      flex: 3,
      justifyContent: 'space-evenly',
      alignItems: 'center',
    },
    view3: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      flex: 5,
    },
    view4: {
      flex: 1,
      justifyContent: 'center',
      marginTop: 10,
      width: '80%',
      alignItems: 'center',
      alignContent: 'center',
      alignSelf: 'center',
    },
    pickLogo: {
      width: 140,
      height: 140,
      backgroundColor: 'white',
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: 'black',
      borderWidth: 3,
      borderRadius: 10,
      borderStyle: 'dashed',
    },
    pickLogoDarkTheme: {
      width: 140,
      height: 140,
      backgroundColor: '#121212',
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
      borderColor: 'white',
      borderWidth: 3,
      borderRadius: 10,
      borderStyle: 'dashed',
    },
    ImageBackground: {
      height: 50,
      width: 50,
      borderRadius: 15,
      position: 'absolute',
      alignSelf: 'center',
    },
    pick: {
      width: 140,
      height: 140,
      borderRadius: 15,
      alignSelf: 'center',
      borderColor: 'black',
    },
    button: {
      backgroundColor: Colors.secondary,
      width: '100%',
      padding: 15,
      borderRadius: 20,
      elevation: 1,
      alignSelf: 'center',
      justifyContent: 'center',
      alignItems: 'center',
    },
    button1: {
      backgroundColor: Colors.secondary,
      width: '60%',
      padding: 10,
      borderRadius: 5,
      justifyContent: 'center',
      alignItems: 'center',
      elevation: 1,
    },
    buttonText: {
      color: 'white',
      fontWeight: '700',
      fontSize: 16,
    },
    selectFoodType: {
      paddingHorizontal: 15,
      marginTop: 15,
      marginBottom: 17,
      borderColor: 'white',
      shadowColor: '#000000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.2,
      shadowRadius: 1.41,
      elevation: 15,
      width: 300,
      height: 50,
      backgroundColor: '#FFFCFB',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 13,
      borderWidth: 1,
    },
    dropdownStyle: {
      backgroundColor: '#FFFCFB',
      width: 300,
      borderBottomLeftRadius: 13,
      borderBottomRightRadius: 13,
    },
  });
  export default styles;