import { StyleSheet, Dimensions } from "react-native";
import Colors from "../../../assets/Colors";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const styles = StyleSheet.create({
  container: {
    height: windowHeight,
    width: windowWidth,
    flex: 1,
    paddingTop: "6%",
  },
  containerHeader: {
    flex: 3,
    width: windowWidth,
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignContent: "center",
    paddingLeft: "2%",
  },
  FlatlistItemContainer: {
    flexDirection: "row",
    flex: 1,
    width: windowWidth,
    justifyContent: "flex-start",
    alignItems: "center",
    margin: 15,
  },
  containerFlatListItemStyle: {
    flex: 1,
    paddingTop: "2%",
    flexDirection: "row",
    width: windowWidth,
    paddingLeft: "5%",
  },
  containerTotals: {
    flex: 1,
    flexDirection: "row",
    paddingLeft: "5%",
    paddingRight: "5%",
  },
  containerDiscount: {
    flex: 1,
    flexDirection: "row",
    paddingLeft: "5%",
    paddingRight: "5%",
    paddingTop: "2%",
  },
  containerItemMapList: {
    flexDirection: "row",
    flex: 1,
    paddingTop: "2%",
    marginTop: "5%",
    height: 70,
    alignItems: "center",
    justifyContent: "center",
  },
  containerNumberDish: {
    justifyContent: "center",
    alignItems: "center",
    alignContent: "center",
    backgroundColor: Colors.primary,
    flex: 1.5,
    borderRadius: 15,
    width: 50,
    height: 50,
    marginRight: "10%",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  containerFlatListStyle: {
    flex: 6,
    paddingHorizontal: "2%",
    marginTop: -150,
    width: windowWidth,
    backgroundColor: "transparent",
  },
  containerBottom: {
    flex: 2.5,
  },
  imgBackgroundSourceStyle: {
    flex: 1,
    resizeMode: "cover",
    width: "100%",
    height: "100%",
  },
  imgTagSourceStyle: {
    width: "100%",
    height: "60%",
    flex: 2.5,
    resizeMode: "cover",
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    paddingRight: "0%",
    marginRight: "0%",
  },
  imgCloseSourceStyle: {
    height: 20,
    width: 20,
    resizeMode: "cover",
    alignSelf: "center",
  },
  btnCloseScreen: {
    paddingTop: "7%",
    flex: 0.5,
    marginLeft: "10%",
    paddingLeft: "10%",
  },
  btnCheckOutStyle: {
    flex: 1,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
    width: windowWidth - 50,
    alignSelf: "center",
    marginBottom: "5%",
    backgroundColor: Colors.primary,
    borderRadius: 40,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  txtTotal: {
    fontSize: 18,
    fontWeight: "bold",
  },
  txtDiscount: {
    fontSize: 15,
  },
  txtTotalInfo: {
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: "72%",
  },
  buttonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
  },
  button: {
    backgroundColor: Colors.secondary,
    width: "100%",
    padding: 15,
    borderRadius: 20,
    elevation: 1,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
  },
  txtTitle: {
    flex: 1,
    marginRight: "0%",
    marginBottom: "0%",
    marginTop: "10%",
    fontSize: 20,
    fontWeight: "bold",
    alignSelf: "center",
  },
  txtDiscountInfo: {
    marginLeft: "40%",
    fontSize: 18,
    fontWeight: "bold",
  },
  txtCheckOutStyle: {
    color: Colors.gray,
    fontSize: 20,
    fontWeight: "bold",
  },
  txtPriceDishItemMap: {
    flex: 1.5,
    fontSize: 18,
    fontWeight: "bold",
    marginLeft: "5%",
    paddingTop: "2%",
  },
  txtNameDishItemMap: {
    flex: 4,
    paddingTop: "2%",
  },
  txtNumberDishItemMap: {
    paddingLeft: "5%",
    color: Colors.lightGray,
    alignSelf: "center",
    fontSize: 18,
  },
  DevideLineStyle: {
    flex: 0.03,
    width: windowWidth,
    height: "0.1%",
    marginTop: "0%",
    marginBottom: "0%",
    backgroundColor: "#AFAFAF",
    alignSelf: "center",
  },
});

export default styles;
