import { StyleSheet, Dimensions } from 'react-native';
import Colors from '../../../assets/Colors';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  container_top: {
    height: 100,
    justifyContent: 'center',
    alignContent: 'center',
    marginTop: '7%',
  },
  container: {
    backgroundColor: '#FFF',
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    justifyContent: 'center',
    height: windowHeight,
  },
  container_bottom: {
    top: 0,
    flexDirection: 'column',
    borderRadius: 20,
    paddingTop: 15,
    marginTop: '0%',
    marginBottom: '13%',
  },
  rectangleGreydevideView: {
    backgroundColor: '#808080',
    width: windowWidth,
    height: 5,
    marginBottom: 10,
    marginTop: 25,
  },
  container_layout_row: {
    flexDirection: 'row',
  },
  container_bottomTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginHorizontal: 0,
    backgroundColor: '#8000',
    height: 60,
    marginLeft: 0,
    paddingLeft: 0,
    paddingRight: 30,
    marginRight: 0,
    width: windowWidth,
    marginBottom: 0,
  },
  container_layout_row1: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    left: 0,
  },
  container_layout_row2: {
    flexDirection: 'row',
    height: 50,
  },
  container_layout_column: {
    flexDirection: 'column',
  },
  container_layout_column2: {
    flexDirection: 'column',
    top: 10,
    bottom: 30,
  },
  container_layout_column3: {
    flexDirection: 'column',
    top: 10,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 50,
  },
  viewMENU: {
    top: 5,
    backgroundColor: 'transparent',
  },
  viewtest: {
    flex: 7,
    backgroundColor: '#F3F3F3',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 20,
    left: 10,
    right: 0,
  },
  btnContainerViewStyle: {
    flexDirection: 'column',
    top: 5,
    justifyContent: 'space-between',
  },
  btnImagestyle: {
    height: 20,
    width: 20,
    left: 70,
  },
  btnBottomTabs: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  flatlistitemStyle: {
    flex: 1,
    flexDirection: 'row',
    top: 1,
    backgroundColor: 'transparent',
  },
  flatlistStyle: {},
  btnOrder: {
    width: 310,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FF6838',
    marginTop: 20,
  },
  btnMenuMainCourse: {
    height: 54,

    borderRadius: 30,
    backgroundColor: '#fff',
    borderColor: '#000',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnMenuDesert: {
    height: 54,
    borderRadius: 30,
    backgroundColor: '#fff',
    borderColor: '#000',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnMenuDrink: {
    height: 54,
    borderRadius: 30,
    backgroundColor: '#fff',
    borderColor: '#000',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTest: {
    width: 310,
    height: 60,

    flexDirection: 'row',
  },
  btnMenuStarter: {
    height: 54,

    borderRadius: 30,
    backgroundColor: '#fff',
    borderColor: '#000',
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnTextstyle: {
    fontSize: 18,

    // width: 175,
    // height: 27,
    fontWeight: 'bold',
  },
  lineStyle: {
    width: 350,
    backgroundColor: '#000000',
    height: 0.6,
    marginTop: 20,
    marginBottom: 20,
  },
  lineStyle2: {
    width: 350,
    backgroundColor: '#808080',
    height: 0.6,
    marginTop: 20,
    marginBottom: 10,
  },
  textMENU: {
    height: 20,
    alignSelf: 'center',
    marginTop: 0,
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: 12,
    fontWeight: 'bold',
    margin: 2,
    top: 0,
  },
  txtOrder: {
    color: '#F6F6F9',
    fontWeight: 'bold',
    fontSize: 18,
  },
  lineStyle1: {
    width: 18,
    height: 2,
    margin: 2,
    alignContent: 'center',
    justifyContent: 'center',
    alignItems: 'center',
    left: 7,
    backgroundColor: '#808080',
  },
  marginFlatlistText: {
    margin: 5,
  },
  textHeaderTab: {
    color: '#ff6838',
    top: -40,
    fontSize: 25,
    bottom: 0,
    fontWeight: 'bold',
  },
  textHeaderBottomMessage: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#ff6838',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  textHeaderBottom: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#ff6838',
  },
  txtinput: {
    width: 115,
    top: 3,
  },
  txtBottomTabHome: {
    fontSize: 15,
    marginTop: 0,
    marginBottom: 0,
  },
  txtBottomTabBill: {
    fontSize: 15,
    marginTop: 0,
  },
  textHeader: {
    fontSize: 30,
    fontWeight: 'bold',
    color: 'black',
    alignSelf: 'center',
    marginBottom: '3%',
  },
  IconHeader: {
    right: 0,
    top: -20,
  },
  appButtonContainer: {
    padding: 10,
    height: 60,
    width: 364,
    top: -10,
    bottom: 100,
    borderRadius: 20,
    backgroundColor: '#F3F3F6',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  appButtonText: {
    width: 175,
    height: 30,
    color: '#000',
  },
  droidSafeArea: {
    flex: 1,
  },
  imgBottomTab: {
    height: 40,
    width: 40,
  },
});
