import { StyleSheet, Dimensions } from 'react-native';
import Colors from '../../../assets/Colors';

const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;

const styles = StyleSheet.create({
  droidSafeArea: {
    flex: 1,
    backgroundColor: '#fff',
    padding: 0,
    justifyContent: 'center',
    elevation: 8,
    margin: 0,
    paddingTop: Platform.OS === 'Android' ? StatusBar.currentHeight : 0,
  },
  container_header: {
    height: 70,
    flexDirection: 'row',
    backgroundColor: '#fff',
    justifyContent: 'space-between',
  },
  containerSearchView: {
    height: 100,
    flexDirection: 'row',
    backgroundColor: '#000',
    justifyContent: 'space-between',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: -20,
  },
  containerImageItem: {
    height: 70,
    width: 78,
    marginLeft: 10,
    padding: 10,
    borderRadius: 20,
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  containerListItemView: {
    padding: 10,
  },
  containerBtnAdjust: {
    justifyContent: 'center',
    flexDirection: 'row',
    elevation: 1,
    marginLeft: 0,
    marginRight: '2%',
  },
  containerBtnApply: {
    backgroundColor: '#F8774A',
    borderRadius: 25,
    height: 40,
    width: 105,
    marginTop: 10,
    marginLeft: 240,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  scrollviewStyle: {
    backgroundColor: '#FFf',
    flexDirection: 'column',
    flex: 1,
  },
  flatlistItemView: {
    height: 110,
    width: 330,
    flex: 1,
    borderRadius: 30,
    borderWidth: 2,
    margin: 5,
    borderColor: '#808080',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
  },
  txtQuantityItem: {
    fontSize: 16,
    marginHorizontal: '2%',
    color: '#3D3D3D',
  },
  txtQuantityItemDarkTheme: {
    fontSize: 16,
    marginHorizontal: '2%',
    color: '#fff',
  },
  txtTitle: {
    marginLeft: 30,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    fontSize: 25,
    fontWeight: 'bold',
  },
  txtBtnApply: {
    fontSize: 14,
    color: '#fff',
  },
  txtInpSearch: {
    marginLeft: 10,
    height: 55,
    marginRight: 10,
    width: 280,
    backgroundColor: '#fff',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E1D9D1',
    paddingLeft: 25,
    fontSize: 18,
    color: '#8A8A8A',
  },

  txtInpSearchDark: {
    marginLeft: 10,
    height: 55,
    marginRight: 10,
    width: 280,
    backgroundColor: '#313133',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#E1D9D1',
    paddingLeft: 25,
    fontSize: 18,
    color: '#8A8A8A',
  },
  txtDetailItemFlatlist: {
    fontSize: 12,
    color: '#3D3D3D',
  },
  txtNameItemFlatlist: {
    fontSize: 16,
    color: '#3D3D3D',
    fontWeight: 'bold',
  },
  txtNameItemFlatlistDarkTheme: {
    fontSize: 16,
    color: '#fff',
    fontWeight: 'bold',
  },
  txtDetailItemFlatlistDarkTheme: {
    fontSize: 12,
    color: '#fff',
  },
  txtPriceItemFlatlist: {
    fontSize: 18,
    color: '#F3554A',
    fontWeight: 'bold',
  },
  btnDel: {
    justifyContent: 'center',
    color: '#FFF',
    fontSize: 16,
    zIndex: 1,
    alignSelf: 'center',
  },
  btnAdd: {
    height: 24,
    width: 24,
    backgroundColor: '#F9881F',
    justifyContent: 'center',
    padding: 10,
    borderRadius: 90,
    alignItems: 'center',
    alignSelf: 'center',
    marginRight: 10,
    marginLeft: 5,
    elevation: 3,
  },
  imgBtnCloseStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginRight: 20,
  },
  imaBtnFillter: {
    marginRight: 10,
  },
  imgBtnOrangeStyle: {
    width: 24,
    height: 24,
    resizeMode: 'cover',
    zIndex: 2,
  },
});
export default styles;
