import { StyleSheet, Dimensions } from "react-native";
import Colors from "../../../assets/Colors";

const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;

const styles = StyleSheet.create({
  droidSafeArea: {
    flex: 1,
    width: windowWidth,
    height: windowHeight,
    padding: 0,
    elevation: 8,
    margin: 0,
    paddingTop: Platform.OS === "Android" ? StatusBar.currentHeight : 0,
  },
  container: {
    marginBottom: "0%",
    paddingTop: "0%",
    backgroundColor: "#fff",
  },
  containerTop: {
    backgroundColor: "#FF4B3A",
    flexDirection: "column",
    alignItems: "center",
    alignContent: "center",
    paddingTop: 20,
  },
  containerBottom: {
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,

    borderColor: "#808080",
    backgroundColor: "#fff",
    justifyContent: "center",
    alignItems: "center",

    marginTop: -40,
    paddingTop: 20,
    paddingLeft: 10,
  },
  txtSearchBar: {
    color: "#8A8A8A",
    maxWidth: 200,
    width: 200,
  },
  txtHeaderView: {
    fontSize: 30,
    fontWeight: "bold",
    marginTop: 0,
    marginBottom: 0,
    paddingTop: 20,
  },
  txtItemFlatlist: {
    color: "#A09A99",
    marginBottom: 10,
    alignSelf: "center",
    fontSize: 20,
  },
  txtItemFlatlistInUse: {
    color: Colors.primary,
    marginBottom: 10,
    alignSelf: "center",
    fontSize: 20,
  },
  containerTemp: {
    flexDirection: "row",
    marginBottom: 50,
    paddingTop: -200,
  },
  containerSearchLayout: {
    width: 280,
    height: 50,
    borderRadius: 15,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "#A09A99",
    backgroundColor: "#fff",
    flexDirection: "row",
    alignItems: "center",
    alignContent: "center",
    padding: 0,
  },
  imgIconSearch: {
    margin: 0,
    height: 16,
    width: 16,
    resizeMode: "cover",
  },
  imgIconFillter: {
    height: 50,
    width: 50,
    margin: 0,
  },
  imgItemFlatlist: {
    height: 70,
    width: 70,
    marginTop: 20,
    marginBottom: 5,
    resizeMode: "cover",
    alignSelf: "center",
    margin: 0,
    borderRadius: 20,
  },
  btnSearch: {
    height: 20,
    width: 20,
    marginLeft: 20,
    marginRight: 10,
  },
  btnImgFillter: {
    height: 50,
    width: 50,
  },
  flatlistitemStyle: {
    height: 130,
    width: 130,
    borderRadius: 20,
    justifyContent: "center",
    borderColor: "grey",
    borderWidth: 2,
    alignItems: "center",
    marginRight: 20,
    marginVertical: 20,
    marginLeft: 10,
  },
  flatlistitemStyleInUse: {
    height: 130,
    width: 130,
    borderRadius: 20,
    justifyContent: "center",
    borderColor: Colors.primary,
    borderWidth: 2,
    alignContent: "center",
    alignItems: "center",
    marginRight: 20,
    marginVertical: 20,
    marginLeft: 10,
  },
  btnUserStyle: {
    height: 30,
    width: 30,
    justifyContent: "center",
    alignContent: "center",
    alignItems: "center",
  },
  button: {
    backgroundColor: Colors.primary,
    width: "45%",
    padding: 15,
    borderRadius: 20,
    elevation: 1,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
    marginHorizontal: "2%",
  },
  button2: {
    backgroundColor: Colors.primary,
    width: "50%",
    padding: 15,
    borderRadius: 20,
    elevation: 1,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  flatlistContainer: {
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    marginTop: -30,
    backgroundColor: "white",
  },
  button1: {
    backgroundColor: Colors.secondary,
    width: "45%",
    padding: 15,
    borderRadius: 20,
    elevation: 1,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
    marginHorizontal: "2%",
  },
  imgUserStyle: {
    height: 25,
    width: 25,
    resizeMode: "cover",
    alignSelf: "center",
  },
  buttonText: {
    color: "white",
    fontWeight: "700",
    fontSize: 16,
  },
});
export default styles;
