import { StyleSheet, Dimensions } from "react-native";
import Colors from "../../../assets/Colors";
const windowWidth = Dimensions.get("window").width;
const windowHeight = Dimensions.get("window").height;
const maxWidthConst = windowWidth - 30;
const styles = StyleSheet.create({
  container: {
    width: windowWidth,
    height: windowHeight,
    flex: 1,
    paddingTop: 0,
    paddingBottom: "7%",
    paddingTop: "5%",
  },
  headerText: { fontSize: 15, color: "#000", fontWeight: "400" },
  headerTextSection: {
    flex: 7,
    alignItems: "flex-start",
    justifyContent: "center",
  },
  headerUsername: {
    fontSize: 25,
    fontWeight: "bold",
    color: "#009DC7",
    marginTop: 5,
  },
  headerUserSection: {
    flex: 3,
    alignItems: "flex-end",
    justifyContent: "flex-end",
    flexDirection: "row",
  },
  headerUserImage: { width: 50, height: 50, borderRadius: 20, marginTop: 5 },
  headerSection: {
    height: 100,
    flexDirection: "row",
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 15,
    marginRight: 15,
  },
  closeButton: {
    // alignSelf: 'center',
    // backgroundColor: 'black',
    // padding: 10,
    // borderRadius: 20,
    // elevation: 20,
    // bottom: '100%',

    backgroundColor: "black",
    width: "30%",
    padding: 12,
    borderRadius: 10,
    justifyContent: "center",
    alignItems: "center",
    elevation: 20,
    alignSelf: "center",
    bottom: "100%",
  },
  closeButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  containerTitleInfo: {
    flex: 4,
    flexWrap: "wrap",
    marginTop: "1%",
    maxWidth: "90%",
    alignItems: "center",
    paddingLeft: "5%",
    justifyContent: "center",
  },
  icUserStyle: {
    height: 40,
    width: 40,
    paddingRight: 10,
    marginRight: "0%",
    alignSelf: "center",
    resizeMode: "cover",
    marginRight: "2%",
  },
  containerHeaderTop: {
    flex: 1,
    flexDirection: "row",
    marginBottom: 0,
  },
  containerMenuInfo: {
    flex: 1,
    flexDirection: "row",
  },
  containerExcDealInfo: {
    flex: 1,
    marginTop: "5%",
    marginLeft: "5%",
  },
  containerHeaderInfoTxt: {
    flex: 1,
    paddingLeft: "8%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  ContainnerTextSaleOff: {
    flex: 1,
    paddingLeft: "8%",
    paddingTop: "10%",
  },
  containerTxtInfo: {
    flex: 2,
  },
  containerHeaderDetailMenuInfoTxt: {
    flex: 1,
    paddingLeft: "6%",
  },
  containerBtnMenuInfo: {
    flex: 2.5,
    width: windowWidth,
    alignContent: "center",
    justifyContent: "center",
    backgroundColor: "transparent",
  },
  containerDevideLine: {
    flex: 0.02,
    width: maxWidthConst,
    height: "1%",
    marginTop: "3%",
    marginBottom: "4%",
    backgroundColor: "#AFAFAF",
    alignSelf: "center",
  },
  containerBtnDealInfo: {
    flex: 2.5,
    marginTop: "0%",
    flexDirection: "row",
    justifyContent: "space-evenly",
    alignItems: "center",
    paddingHorizontal: "4%",
  },
  containerExcDealsHeader: {
    flex: 0.5,
    maxWidth: maxWidthConst,
  },
  containerBtnExcDeals: {
    flex: 3,
    backgroundColor: "transparent",
    maxWidth: windowWidth,
    justifyContent: "center",
    alignContent: "center",
  },
  icHomeStyle: {
    height: 60,
    width: 60,
    flex: 1,
    top: 5,
  },

  imgSaleOff: {
    flex: 1,
    resizeMode: "contain",
    zIndex: 1,
    height: "100%",
    width: "100%",
    top: "5%",
    left: "20%",
  },
  imgTryNew: {
    flex: 1,
    resizeMode: "cover",
    zIndex: 1,
    height: "75%",
    width: "75%",
    top: "5%",
    left: "25%",
  },
  imgBackgroundMenuInfo: {
    flex: 1.5,
    marginLeft: 5,
    backgroundColor: "transparent",
    marginTop: 15,
  },
  imgExcDeal: {
    flex: 1.1,
    top: "8%",
    height: "100%",
    width: "100%",
    resizeMode: "contain",
  },
  imgBackgroundMenuInfostyle: {
    height: "105%",
    width: "100%",
    flex: 1,
    zIndex: 1,
    marginRight: 0,
    resizeMode: "cover",
  },
  txtExclDealerText: {
    flex: 1,
    marginLeft: "5%",
    fontSize: 20,
    fontWeight: "bold",
  },
  txtMenu: {
    color: "#FFF",
    fontSize: 30,
    fontWeight: "bold",
  },
  btnSaleOffOpen: {
    flex: 1,
    borderRadius: 15,
    marginRight: "1.1%",
    shadowColor: "#f981a1",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  btnTryNewDishOpen: {
    flex: 1,
    borderRadius: 15,
    marginLeft: "1.1%",
    shadowColor: "#f8bcd5",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  btnMenuOpen: {
    width: maxWidthConst,
    height: "95%",
    alignSelf: "center",
    backgroundColor: "transparent",
    borderRadius: 15,
    shadowColor: Colors.fieryRose,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
  btnBottomOpen: {
    height: "95%",
    width: maxWidthConst,
    alignSelf: "center",
    flexDirection: "row",
    borderRadius: 15,
    shadowColor: "#fb6c74",
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,

    elevation: 3,
  },
});
export default styles;
